name: Free up space in the runner
runs:
  using: "composite"
  steps:
    - name: Free up space
      shell: bash
      run: |
        df -h
        echo
        echo Freeing up space
        rm -rf .git/
        docker system prune --force
        docker rmi $(docker image ls -aq) || true
        docker system prune --force
        export DEBIAN_FRONTEND="noninteractive"
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /opt/microsoft /opt/google
        sudo rm -rf /opt/az
        sudo rm -rf /usr/local/share/powershell
        echo
        df -h
