#!/usr/bin/env bash

set -e
source "${BASH_SOURCE%/*}"/lib

usage="$0 [OPTION]... IMAGESDIR [VERSION]

Build the Docker images under the IMAGESDIR directory.
Label each built image with the given VERSION number (default: latest).
The build takes advantage of any reusable layer from previously built images.

Options:

    -h              Show this help message.
    -p              Publish each built image to the GitHub Container Registry
                    (you need to be logged in to ghcr.io with the appropriate
                    permissions for this to work)."

helpflag=
publishflag=

while getopts hp name; do
    case $name in
        h) helpflag=1 ;;
        p) publishflag=1 ;;
        *) error "Invalid option. Use the -h flag for more information." ;;
    esac
done

shift $((OPTIND - 1))

if [[ -n $helpflag ]]; then
    echo "$usage"
    exit
fi

if [[ $# -eq 0 ]]; then
    error "Missing IMAGESDIR arguments. Use the -h flag for more information."
fi

if [[ $# -gt 2 ]]; then
    error "Extraneous arguments. Use the -h flag for more information."
fi

imagesdir="$1"
version="$2"

# Enable BuildKit for better cache behavior
# See <https://docs.docker.com/engine/reference/builder/#buildkit>
export DOCKER_BUILDKIT=1

docker-build() {
    from="$(image-name "$1" "$version")"
    target="$(image-name "$2" "$version")"
    status "Building image '$target'"
    docker image build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg FROM="$from" \
        --cache-from "$(image-name "$2")" \
        --tag "$target" .

    if [[ -n $publishflag ]]; then
        docker image push "$target"
    fi
}

pushd "$imagesdir"/toolchain
docker-build toolchain toolchain
popd

# pushd "$imagesdir"/base
# docker-build toolchain base
# popd

# pushd "$imagesdir"/golang
# docker-build base golang
# popd

# pushd "$imagesdir"/python
# docker-build base python
# popd

# pushd "$imagesdir"/qt
# docker-build base qt
# popd

# pushd "$imagesdir"/rust
# docker-build base rust
# popd

status "Done"
